services:
  theleagues-db-container:
    image: postgres:16
    container_name: theleagues-db-dev
    restart: always
    environment:
      POSTGRES_USER: ${THELEAGUES_ROOT_USER}
      POSTGRES_PASSWORD: ${THELEAGUES_ROOT_PASSWORD}
      POSTGRES_DB: ${THELEAGUES_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$THELEAGUES_ROOT_USER -d $$THELEAGUES_DB_NAME"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./DATA:/var/lib/postgresql/data

  home-api-container:
    build:
      context: .
      dockerfile: HomeAPI/home-api-dockerfile
    container_name: home-api-dev
    depends_on:
      theleagues-db-container:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - THELEAGUES_DB_HOST=theleagues-db-container
      - THELEAGUES_DB_PORT=5432
      - THELEAGUES_DB_NAME=${THELEAGUES_DB_NAME}
      - THELEAGUES_ROOT_USER=${THELEAGUES_ROOT_USER}
      - THELEAGUES_ROOT_PASSWORD=${THELEAGUES_ROOT_PASSWORD}
    ports:
      - "5001:8080"

  away-api-container:
    build:
      context: .
      dockerfile: AwayApi/away-api-dockerfile
    container_name: away-api-dev
    depends_on:
      theleagues-db-container:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - THELEAGUES_DB_HOST=theleagues-db-container
      - THELEAGUES_DB_PORT=5432
      - THELEAGUES_DB_NAME=${THELEAGUES_DB_NAME}
      - THELEAGUES_ROOT_USER=${THELEAGUES_ROOT_USER}
      - THELEAGUES_ROOT_PASSWORD=${THELEAGUES_ROOT_PASSWORD}
    ports:
      - "5002:8080"

  theleagues-ui-container:
    build:
      context: .
      dockerfile: TheLeaguesUI/ui-dockerfile
    container_name: thleagues-ui-dev
    ports:
      - "80:80" # Changed to 80 so you can just visit http://localhost
    environment:
      - HomeAPIUrl=http://localhost:5001
      - AwayAPIUrl=http://localhost:5002